CREATE TABLE Admin (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
Token VARCHAR(255) NOT NULL);

CREATE TABLE Appointment (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PairId INT(6),
TopicId INT(6) NOT NULL,
ScheduledAt DATETIME NOT NULL,
Status VARCHAR(255) NOT NULL,
Created DATETIME NOT NULL,
LastUpdate DATETIME NOT NULL);

CREATE TABLE AppointmentSummary (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
AppointmentId INT(6),
SummaryText VARCHAR(255)) NOT NULL,
UserId INT(6),
Status VARCHAR(255) NOT NULL,
Created DATETIME NOT NULL,
LastUpdate DATETIME NOT NULL);

CREATE TABLE Pair (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
MentorId INT(6),
MenteeId INT(6),
Created DATETIME NOT NULL,
LastUpdate DATETIME NOT NULL,
PrivacyAccepted INT(6));

CREATE TABLE Topic (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PostedBy INT(6),
DueDate DATETIME NOT NULL,
Title VARCHAR(255) NOT NULL,
Description VARCHAR(255) NOT NULL,
Created DATETIME NOT NULL,
LastUpdate DATETIME NOT NULL,
ActiveTopic INT(6));

CREATE TABLE User (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Token VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
Avatar VARCHAR(255) NOT NULL,
ExpoPushToken VARCHAR(255) NOT NULL,
Created DATETIME NOT NULL,
LastUpdate DATETIME NOT NULL,
PrivacyAccepted INT(6),
Approved INT(6));

CREATE TABLE UserContact (
Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
UserId INT(6),
ContactValue VARCHAR(255) NOT NULL,
ContactType VARCHAR(255) NOT NULL,
Created DATETIME NOT NULL,
LastUpdate DATETIME NOT NULL);
